name: Build Potassium

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: gradle

      - name: Make Gradle bootstrap executable
        run: chmod +x gradlew

      - name: Build Potassium
        run: ./gradlew setupDecompWorkspace build --no-daemon --stacktrace

      - name: Upload Potassium JAR
        uses: actions/upload-artifact@v4
        with:
          name: Potassium-${{ github.ref_name }}-${{ github.sha }}
          path: build/libs/*.jar
          if-no-files-found: error
